
# ======================================================================================================================
# CUSTOM CONFIGS
# ======================================================================================================================
spp:
    app:
        conf:
            file:
                support-data: data/support-data.xlsx

# ======================================================================================================================
# SPRING CONFIGS
# ======================================================================================================================
server:
    port: 8003
    servlet:
        # Let's customise the app's context path.
        context-path: /interstellar

spring:
    autoconfigure:
        # Let's switch of the Error White Label, so that we can have fun with Swagger, I mean why not?
        exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

    # Database Configs
    datasource:
        url: jdbc:postgresql://localhost:5432/shortest_path
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        driverClassName: org.postgresql.Driver

    # Hibernate Configs
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect