



# ======================================================================================================================
# SPRING CONFIGS
# ======================================================================================================================
spring:
    docker:
        compose:
            file: src/docker/compose-postgres.yml