services:
  postgres:
    container_name: shortest-postgres-db
    image: postgres:16-alpine3.19
    ports:
      - 5433:5432
    restart: unless-stopped
    environment:
      - POSTGRES_DB=shortest_path
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - network

networks:
  network:
    driver: bridge
    name: shortest-postgres-database-network
