services:
  shortest-path-application:
    container_name: shortest-path-app
    image: localhost:5002/shortest-path-app:latest
    ports:
      - 8003:8003
    restart: unless-stopped
    environment:
      # To clear the manifest using the HTTP API you need to set REGISTRY_STORAGE_DELETE_ENABLED = true
      # in your postgres-compose file and make sure that you are using a registry V2.
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_HOST: shortest-postgres-db
      DATABASE_PORT: "${DATABASE_PORT}"

    networks:
      - shortest-path-app-network

# Get it to connect to
networks:
  shortest-path-app-network:
    name: shortest-postgres-database-network
    external: true
