version: '3.9'

services:
  registry:
    container_name: registry
    image: registry:2.8.3
    ports:
      - 5001:5000
    restart: unless-stopped
    environment:
      # To clear the manifest using the HTTP API you need to set REGISTRY_STORAGE_DELETE_ENABLED = true
      # in your docker-compose file and make sure that you are using a registry V2.
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - ~/docker/app-volumes/registry:/var/lib/registry
