apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.generalInfo.namespace }}
  name: {{ .Values.environmentData.applicationConfigName }}
data:
  application.json: |
    {
      "spp": {
        "app": {
          "conf": {
            "file": {
              "support-data": "data/support-data.xlsx"
            }
          }
        },
        "server": {
          "port": 8003,
          "servlet": {
            "context-path": "/interstellar"
          }
        },
        "spring": {
          "autoconfigure": {
            "exclude": "org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration"
          },
          "datasource": {
            "url": "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/shortest_path",
            "username": "${DATABASE_USERNAME}",
            "password": "${DATABASE_PASSWORD}",
            "driverClassName": "org.postgresql.Driver"
          },
          "jpa": {
            "hibernate": {
              "ddl-auto": "none"
            },
            "properties": {
              "hibernate": {
                "dialect": "org.hibernate.dialect.PostgreSQLDialect"
              }
            }
          }
        }
      }
    }