apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: toob-space
  name: shortest-path-app-deployment
  labels:
    app: shortest-path-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortest-path-app
  template:
    metadata:
      labels:
        app: shortest-path-app
    spec:
      containers:
        - name: shortest-path-app
          image: localhost:5001/shortest-path-app:latest
          ports:
            - containerPort: 8003
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secrets
                  key: db-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secrets
                  key: db-password
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: shortest-path-app-config
                  key: application.json
---
apiVersion: v1
kind: Service
metadata:
  namespace: toob-space
  name: shortest-path-app-service
spec:
  type: LoadBalancer
  selector:
    app: shortest-path-app
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003