# Default values for app-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



# ======================================================================================================================
# SHORTEST PATH APPLICATION
# ======================================================================================================================

generalInfo:
  labelName: shortest-path-app
  namespace: toob-space

appInfo:
  deploymentName: shortest-path-app-deployment
  serviceName: shortest-path-app-service
  containerInfo:
    name: shortest-path-app
    imageName: localhost:5001/shortest-path-app:latest
    port: 8003

registryInfo:
  deploymentName: shortest-registry-deployment
  serviceName: shortest-registry-service
  containerInfo:
    name: shortest-registry
    imageName: registry:2.8.3
    port: 5002

databaseInfo:
  deploymentName: shortest-postgres-deployment
  serviceName: shortest-postgres-service
  databaseName: shortest_path
  host: shortest-postgres-service
  port: 5433
  containerInfo:
    name: shortest-postgres-db
    imageName: postgres:16-alpine3.19
    port: 5433


environmentData:
  databaseSecretsName: postgres-db-secrets
  applicationConfigName: application-json-config
  envarConfigName: envar-config



# ======================================================================================================================
# ORIGINAL SECTION HERE
# ======================================================================================================================

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: app-charts-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

